// Between Us — the question deck. Pure content, no app logic.
// Edited here, loaded by every build (public / work / dev) — one copy, always in sync.

const COLBERT_CARDS = [
  { level: "colbert", question: "What's the best sandwich?", nl: "Wat is de beste boterham?" },
  { level: "colbert", question: "Something you own that you really should throw out...", nl: "Wat is één ding dat je bezit en eigenlijk weg zou moeten gooien?" },
  { level: "colbert", question: "What is the scariest animal?", nl: "Wat is het engste dier?" },
  { level: "colbert", question: "Apples or oranges?", nl: "Appels of sinaasappels?" },
  { level: "colbert", question: "Have you ever asked someone for their autograph?", nl: "Heb je ooit iemand om een handtekening gevraagd?" },
  { level: "colbert", question: "What do you think happens when we die?", nl: "Wat denk je dat er gebeurt als we sterven?" },
  { level: "colbert", question: "Favourite action movie?", nl: "Favoriete actiefilm?" },
  { level: "colbert", question: "Window or aisle?", nl: "Raam of gangpad?" },
  { level: "colbert", question: "Favourite smell?", nl: "Lievelingsgeur?" },
  { level: "colbert", question: "Least favourite smell?", nl: "Minst favoriete geur?" },
  { level: "colbert", question: "Exercise: worth it?", nl: "Sporten: de moeite waard?" },
  { level: "colbert", question: "Flat or sparkling?", nl: "Plat of bruisend?" },
  { level: "colbert", question: "Most used app on your phone?", nl: "Meest gebruikte app op je telefoon?" },
  { level: "colbert", question: "Earliest memory?", nl: "Vroegste herinnering?" },
  { level: "colbert", question: "Cats or dogs?", nl: "Katten of honden?" },
  { level: "colbert", question: "You get one song to listen to for the rest of your life: what is it?", nl: "Je krijgt één nummer om voor de rest van je leven naar te luisteren: wat is het?" },
  { level: "colbert", question: "What number am I thinking of?", nl: "Welk getal denk ik aan?" },
  { level: "colbert", question: "Describe the rest of your life in 5 words.", nl: "Beschrijf de rest van je leven in 5 woorden." },
];

const NEWDECK_CARDS = [

  // ─── QUICK ───
  { level: "quick", question: "Name the last thing you made with your hands.", nl: "Het laatste dat je maakte met je eigen handen..." },
  { level: "quick", question: "What song's been stuck in your head this week?", nl: "Welk liedje krijg je deze week je hoofd niet uit?" },
  { level: "quick", question: "What's your greatest extravagance?", nl: "Wat is je grootste extravagantie?" },
  { level: "quick", question: "Which drawer in your house is the disgrace?", nl: "Welke kast of lade thuis mag dicht blijven?" },
  { level: "quick", question: "You're always late for...", nl: "Waar kom jij structureel te laat?" },
  { level: "quick", question: "What smell makes you instantly hungry?", nl: "Van welke geur krijg je meteen honger?" },
  { level: "quick", question: "What's the strangest thing someone might find in your bag?", nl: "Wat is het vreemdste dat iemand in jouw tas zou kunnen vinden?" },
  { level: "quick", question: "What nickname do you go by — and who gave it?", nl: "Welke bijnaam heb je — en van wie kreeg je die?" },
  { level: "quick", question: "Which texture can you not stop touching?" },
  { level: "quick", question: "What's the most childish thing that still delights you?", nl: "Wat is het meest kinderlijke dat je nog steeds blij maakt?" },
  { level: "quick", question: "Which season fits you best — and how does it show?", nl: "Welk seizoen lijkt het meest op jou?" },
  { level: "quick", question: "What do you quietly fix or straighten in other people's houses?" },

  // ─── WARM ───
  { level: "warm", question: "Some small thing you do properly, though nobody would ever check...", nl: "Iets waar jij meer zorg aan besteedt dan nodig is..." },
  { level: "warm", question: "One small thing can ruin your entire morning. Which?", nl: "Wat kan je stemming in tien seconden verpesten?" },
  { level: "warm", question: "Whose cooking do you miss?", nl: "Naar welk gerecht verlang je soms terug?" },
  { level: "warm", question: "Point to something you're wearing that has a story.", nl: "Iets dat je vandaag draagt en waar een verhaal aan vastzit..." },
  { level: "warm", question: "What do you know a suspiciously specific amount about?", nl: "Waar weet jij verdacht veel specifieks over?" },
  { level: "warm", question: "Which stranger do you still remember fondly?", nl: "Een ontmoeting die maar kort duurde, maar je is bijgebleven..." },
  { level: "warm", question: "Is there something you're genuinely bad at that you still refuse to stop doing?", nl: "Is er iets waar je echt slecht in bent en toch niet mee stopt?" },
  { level: "warm", question: "When's the last time you watched someone do something and thought, I wish I could do that?", nl: "Wanneer zag je voor het laatst iemand iets doen en dacht je: dat zou ik ook willen kunnen?" },
  { level: "warm", question: "What have you repaired instead of replaced — and why?", nl: "Wat heb je gerepareerd terwijl vervangen makkelijker was?" },
  { level: "warm", question: "What do you knowingly blow out of proportion?", nl: "Waar maak jij bewust meer drama van dan nodig?" },
  { level: "warm", question: "When did you last go gloriously too far — and was it worth it?", nl: "Wanneer sloeg jouw enthousiasme volledig op hol?" },
  { level: "warm", question: "Quote the sentence people around you are most tired of hearing from you.", nl: "Welke uitspraak zouden mensen graag een tijdje niet meer uit jouw mond horen?" },

  // ─── CULTURE ───
  { level: "culture", question: "Which piece of art still does something to you, every time?", nl: "Welk kunstwerk doet nog steeds iets met je, elke keer weer?" },
  { level: "culture", question: "Something universally loved leaves you completely cold...", nl: "Waar begrijpt bijna iedereen de hype van, behalve jij?" },
  { level: "culture", question: "What's a piece of clothing that changes how you carry yourself the second you put it on?", nl: "Welk kledingstuk verandert hoe je je draagt, zodra je het aantrekt?" },
  { level: "culture", question: "When did you last change your mind about something you'd dismissed on sight?", nl: "Wanneer veranderde je van gedachten over iets dat je meteen had afgeschreven?" },
  { level: "culture", question: "What's a place, open to everyone, you'd take someone if you wanted to impress them without saying a word?", nl: "Naar welke plek, toegankelijk voor iedereen, zou je iemand meenemen als je indruk wilde maken zonder iets te zeggen?" },
  { level: "culture", question: "Do you use music to feel more, or to feel less?", nl: "Zet jij muziek aan om ergens in te verdwijnen, of juist om iets te voelen?" },
  { level: "culture", question: "Is taste something you have or something you build?", nl: "Welke smaak moest bij jou groeien?" },
  { level: "culture", question: "What's something you appreciate far more now that you understand how it actually works?", nl: "Wat waardeer je veel meer nu je begrijpt hoe het echt werkt?" },
  { level: "culture", question: "Does great art excuse a terrible artist?", nl: "Pleit grote kunst een slecht mens vrij?" },
  { level: "culture", question: "When did beauty catch you completely unprepared?" },
  { level: "culture", question: "Take us to the moment a story last made you cry." },
  { level: "culture", question: "Is there a piece of culture — book, show, song — you've deliberately not finished, because you don't want it to be over?", nl: "Is er iets — een boek, serie, nummer — dat je expres niet hebt afgemaakt, omdat je niet wilt dat het voorbij is?" },

  // ─── LIFE ───
  { level: "life", question: "Walk me through your first thirty minutes after waking — the real version.", nl: "Je ochtend begint meestal met..." },
  { level: "life", question: "What would have to change for your life to feel more like your own?", nl: "Wat zou er moeten veranderen om je leven meer als het jouwe te laten voelen?" },
  { level: "life", question: "Which chore do you secretly not mind?", nl: "Welke klus vind jij minder vervelend dan de meeste mensen?" },
  { level: "life", question: "Describe your ideal ordinary day — not a holiday, just a Tuesday that felt right.", nl: "Beschrijf je ideale gewone dag — geen vakantie, gewoon een dinsdag die goed voelde." },
  { level: "life", question: "What takes up far more of your life than anyone would guess?" },
  { level: "life", question: "What's something you've done that cost you something — and that you'd do exactly the same again?", nl: "Wat heb je gedaan dat je iets kostte — en wat je precies zo weer zou doen?" },
  { level: "life", question: "What's something you're doing right now without knowing if it'll actually work out?", nl: "Wat doe je nu, zonder te weten of het gaat lukken?" },
  { level: "life", question: "What are you putting off that you know you'll regret?", nl: "Wat blijft maar op je lijstje staan?" },
  { level: "life", question: "What does getting older take from you that you didn't expect, and what does it give?", nl: "Wat neemt ouder worden je af dat je niet had verwacht — en wat geeft het?" },
  { level: "life", question: "What's something completely ordinary in your life right now that you'd genuinely miss if it vanished tomorrow?", nl: "Wat is iets heel gewoons in je leven dat je echt zou missen als het morgen verdween?" },
  { level: "life", question: "What's different about your life this year?", nl: "Wat is er dit jaar anders aan je leven?" },
  { level: "life", question: "If you stopped explaining why you can't, what would change about how you live?", nl: "Als je stopte met uitleggen waarom iets niet kan, wat zou er dan veranderen aan hoe je leeft?" },

  // ─── HOME ───
  { level: "home", question: "Who is allowed in your home unannounced?", nl: "Bij wie hoeft de deurbel eigenlijk niet?" },
  { level: "home", question: "When did a place last stop feeling like home — like you didn't belong?" },
  { level: "home", question: "What object in your house has survived the most versions of you?", nl: "Welk voorwerp in je huis heeft de meeste versies van jou overleefd?" },
  { level: "home", question: "Where in your home do you actually live — which chair, which corner?", nl: "Waar in huis speelt jouw leven zich echt af?" },
  { level: "home", question: "What does home actually feel like when you have it — and how do you know?", nl: "Hoe voelt thuis echt als je het hebt — en hoe weet je dat?" },
  { level: "home", question: "What actually makes you feel at ease somewhere new — and how long does it usually take?" },
  { level: "home", question: "If I walked into your home right now, what would I find?", nl: "Als ik nu je huis binnenliep, wat zou ik aantreffen?" },
  { level: "home", question: "The view from your kitchen window — what could you look at every day and never tire of?", nl: "Het uitzicht uit je keukenraam waar je nooit op uitgekeken raakt — wat is het?" },
  { level: "home", question: "Your home tells people something about you. What?", nl: "Wat vertelt jouw huis over jou voordat jij iets hebt gezegd?" },
  { level: "home", question: "Where would you live if nothing was stopping you — and what would you live in?" },
  { level: "home", question: "Which house from your life do you still walk through in dreams?", nl: "In welk huis uit je verleden kom je nog steeds terug?" },
  { level: "home", question: "Who have you shared a home with — and what did it teach you?", nl: "Met wie heb je een huis gedeeld — en wat leerde je daarvan?" },

  // ─── ROOTS ───
  { level: "roots", question: "The emotional weather in the house you grew up in...", nl: "Hoe was de sfeer bij jullie thuis als je terugkijkt?" },
  { level: "roots", question: "Who did you grow up alongside — and what did they teach you about yourself?" },
  { level: "roots", question: "What did you learn about money in the house you grew up in?", nl: "Wat heb je over geld geleerd in het huis waar je opgroeide?" },
  { level: "roots", question: "The day you finally understood something your parent did...", nl: "De dag dat je eindelijk iets begreep wat je ouder deed..." },
  { level: "roots", question: "What did your upbringing give you that you're glad of?", nl: "Wat heeft je opvoeding je gegeven waar je blij mee bent?" },
  { level: "roots", question: "Look at a photo of young you — what looks back?", nl: "Als je een foto van jezelf als kind ziet, wat valt je dan op?" },
  { level: "roots", question: "Who from school could still make you feel like a kid again if you ran into them today?", nl: "Bij wie van school zou je je nu nog steeds weer een kind voelen als je diegene tegenkwam?" },
  { level: "roots", question: "At home, to be safe, you had to be...", nl: "Wat moest je thuis zijn om problemen te voorkomen?" },
  { level: "roots", question: "What did you play with until it fell apart?" },
  { level: "roots", question: "What did you learn about love from watching your parents?", nl: "Wat leerde je over liefde door naar je ouders te kijken?" },
  { level: "roots", question: "The moment you realised your normal wasn't — take us back." },
  { level: "roots", question: "Which adult from your childhood were you never quite safe with?", nl: "Bij welke volwassene uit je jeugd voelde je je nooit helemaal veilig?" },

  // ─── PAST ───
  { level: "past", question: "What's the decision you almost didn't make that changed everything?", nl: "Welke beslissing had je bijna niet genomen — en veranderde alles?" },
  { level: "past", question: "What phase are you in that you can already tell you'll look back on?", nl: "In welke fase zit je nu waarvan je al weet dat je erop terug zult kijken?" },
  { level: "past", question: "Tell about a time you surprised yourself with what you could survive.", nl: "Een moment waarop je sterker bleek dan verwacht..." },
  { level: "past", question: "What kept you somewhere long after you knew you should leave?" },
  { level: "past", question: "Trace the moment money started meaning something different to you.", nl: "Wanneer kreeg geld een andere betekenis?" },
  { level: "past", question: "Which teacher saw something in you — or missed it entirely?" },
  { level: "past", question: "Which version of yourself was hardest to let go of?", nl: "Welke versie van jezelf was het moeilijkst om los te laten?" },
  { level: "past", question: "Describe a failure you're only now able to talk about.", nl: "Mislukken werd later pas een verhaal. Welke mislukking?" },
  { level: "past", question: "What's the best trouble you ever got into?" },
  { level: "past", question: "Which scar still carries the best story?", nl: "Dat litteken heeft een verhaal." },
  { level: "past", question: "Which year of your life simply vanished?", nl: "Welk jaar lijkt verdwenen zonder dat je het doorhad?" },
  { level: "past", question: "If your younger self could see your life right now, what would surprise them most?", nl: "Als je jongere zelf je leven nu kon zien, wat zou hen het meest verbazen?" },

  // ─── UNWIND ───
  { level: "unwind", question: "When did you last stay outside longer than you meant to — and where were you?" },
  { level: "unwind", question: "What's something you do now for fun that would've bored you stiff ten years ago?", nl: "Wat doe je nu voor je plezier waar je je tien jaar geleden dood zou hebben verveeld?" },
  { level: "unwind", question: "What reliably gets you out of your own head?", nl: "Wat haalt jou altijd betrouwbaar uit je eigen hoofd?" },
  { level: "unwind", question: "The hour of the week that's entirely yours..." },
  { level: "unwind", question: "What's the difference between a day you needed and a day you just let slip by?", nl: "Wat is het verschil tussen een dag die je nodig had en een dag die gewoon voorbijgleed?" },
  { level: "unwind", question: "There was a moment you felt completely free. Where were you?" },
  { level: "unwind", question: "What does travel give you that staying home never could?", nl: "Wat geeft reizen je dat thuisblijven nooit zou kunnen geven?" },
  { level: "unwind", question: "The most unexpected beauty a trip ever handed you..." },
  { level: "unwind", question: "Describe a moment recently when life felt uncomplicated.", nl: "Beschrijf een recent moment waarop het leven simpel voelde." },
  { level: "unwind", question: "A place you keep going back to — not because it's the best, but because it's yours...", nl: "Naar welke plek blijf je teruggaan omdat die van jou voelt?" },
  { level: "unwind", question: "What's the smallest thing that makes a day better — and where do you find it?" },
  { level: "unwind", question: "What does the first warm day of the year do to you?" },

  // ─── SELF ───
  { level: "self", question: "Two traits of yours that seem to work against each other..." },
  { level: "self", question: "Which compliment do you deflect because part of you suspects it's true?", nl: "Welk compliment geloof je niet helemaal?" },
  { level: "self", question: "When are you most lonely — and is anyone around when it happens?", nl: "Wanneer voel je je het eenzaamst — en is er dan iemand in de buurt?" },
  { level: "self", question: "What did someone once point out about you that you now see everywhere?" },
  { level: "self", question: "Who decided they didn't like you — and did you let it go?" },
  { level: "self", question: "When has having power over someone made you kinder, not crueler?", nl: "Wanneer maakte macht over iemand je vriendelijker, niet wreder?" },
  { level: "self", question: "What's something you used to associate with being \"old\" that you now just call Tuesday?", nl: "Wat associeerde je vroeger met 'oud zijn', maar noem je nu gewoon een dinsdag?" },
  { level: "self", question: "There was a time you completely lost your footing. What held — and what did you rebuild first after?", nl: "Er was een tijd dat je de grond onder je voeten verloor. Wat hield je overeind — en wat bouwde je daarna als eerste weer op?" },
  { level: "self", question: "What have you had to accept that you never chose?", nl: "Wat heb je moeten accepteren wat je nooit gekozen hebt?" },
  { level: "self", question: "Strip away the job, the roles, the routines — what's left standing?", nl: "Zonder functie, status of prestaties. Wie blijft er over?" },
  { level: "self", question: "What's something true about you that took far too long to notice?", nl: "Wat is iets waars over jezelf dat je veel te lang niet doorhad?" },
  { level: "self", question: "What holds you up that isn't a person?" },

  // ─── BODY ───
  { level: "body", question: "When did your body surprise you with what it could do?", nl: "Wanneer verraste je lichaam je met wat het kon?" },
  { level: "body", question: "When does your body feel like it belongs to you?", nl: "Wanneer voelt je lichaam alsof het van jou is?" },
  { level: "body", question: "When did you last move purely for the joy of it — no goal, no fitness?", nl: "Wanneer bewoog je voor het laatst puur voor het plezier — geen doel, geen work-out?" },
  { level: "body", question: "What music reaches your body before it reaches your head — and what happens?", nl: "Welke muziek bereikt je lichaam eerder dan je hoofd — en wat gebeurt er dan?" },
  { level: "body", question: "Point to where you carry your tension right now." },
  { level: "body", question: "What did pain teach you that you couldn't have learned any other way?" },
  { level: "body", question: "Point to the part of your body you have the most difficult relationship with — then the one you'd defend as beautiful.", nl: "Wijs de plek op je lichaam aan waar je de moeizaamste relatie mee hebt — en dan de plek die je als mooi zou verdedigen." },
  { level: "body", question: "Which version of your body do you still compare this one to?" },
  { level: "body", question: "What is your body better at now than it has ever been?" },
  { level: "body", question: "What's your actual relationship with food?", nl: "Eten en jij..." },
  { level: "body", question: "Your body asks for something you routinely deny it...", nl: "Je lichaam vraagt regelmatig om iets waar je niet naar luistert." },
  { level: "body", question: "When did your body last let you down?" },

  // ─── MIND ───
  { level: "mind", question: "How easily does a new habit stick for you — and which one actually did?", nl: "Hoe makkelijk beklijft een nieuwe gewoonte bij jou — en welke is echt blijven hangen?" },
  { level: "mind", question: "What do you consistently resist — and when does that break down?" },
  { level: "mind", question: "Which thought loop do you know is a loop and still can't exit?", nl: "Een gedachte waar je telkens opnieuw in vastloopt..." },
  { level: "mind", question: "When has a gut feeling known more than you did?", nl: "Wanneer wist een onderbuikgevoel meer dan jij?" },
  { level: "mind", question: "Silence, no phone, nothing to do — how long before you actually start enjoying it?", nl: "Stilte, geen telefoon, niets te doen — hoe lang duurt het voor je dat echt begint te genieten?" },
  { level: "mind", question: "What does your inner voice sound like — and whose is it?", nl: "Hoe klinkt je innerlijke stem — en van wie is die?" },
  { level: "mind", question: "Which of your opinions is just something you heard once?", nl: "Welke van jouw meningen heb je eigenlijk ooit ergens opgepikt?" },
  { level: "mind", question: "What's the last thing that annoyed you that you'd be a little embarrassed to admit annoyed you?", nl: "Wat is het laatste dat je irriteerde waarvan je je een beetje zou schamen dat het je irriteerde?" },
  { level: "mind", question: "What's the earliest thing you remember — and is it actually yours?", nl: "Wat is je vroegste herinnering — en is die eigenlijk wel van jou?" },
  { level: "mind", question: "Which question do you keep returning to across the years?", nl: "Welke vraag blijft met je meelopen?" },
  { level: "mind", question: "What are you bad at learning?", nl: "Waar ben je slecht in om te leren?" },
  { level: "mind", question: "What are you like at three in the morning?" },

  // ─── SPIRIT ───
  { level: "spirit", question: "What were you taught to believe — and what's left of it?", nl: "Wat is je geleerd om te geloven — en wat is daarvan over?" },
  { level: "spirit", question: "Is your life meaningful right now — and how do you know?", nl: "Heeft je leven op dit moment betekenis — en waaraan merk je dat?" },
  { level: "spirit", question: "What's your working relationship with death, right now?", nl: "Hoe vaak denk je aan je eigen einde?" },
  { level: "spirit", question: "Is there a philosophy or teaching you've borrowed from, without signing up to all of it?", nl: "Is er een filosofie of leer waar je uit put, zonder je er helemaal aan te verbinden?" },
  { level: "spirit", question: "When did you last feel part of something larger — and what triggered it?", nl: "Wanneer voelde jij je voor het laatst onderdeel van iets dat groter was dan jezelf?" },
  { level: "spirit", question: "How near has death actually come to you?", nl: "De dood kwam dichterbij dan je lief was. Wanneer?" },
  { level: "spirit", question: "Who are you overdue to thank — and what for?", nl: "Wie zou je allang bedankt moeten hebben — en waarvoor?" },
  { level: "spirit", question: "What do you hope is true, even if you doubt it?", nl: "Wat hoop je dat waar is, ook al twijfel je eraan?" },
  { level: "spirit", question: "When were you last completely present — nothing to fix, nothing to plan?", nl: "Wanneer was je voor het laatst volledig aanwezig — niets op te lossen, niets te plannen?" },
  { level: "spirit", question: "Have you ever tried to reach something through your body — breath, fasting, dance, stillness?", nl: "Heb je ooit iets proberen te bereiken via je lichaam — ademhaling, vasten, dans, stilte?" },
  { level: "spirit", question: "A place that's sacred to you..." },
  { level: "spirit", question: "The closest thing I have to a ritual is...", nl: "Een ritueel dat ongemerkt belangrijk voor je werd..." },


  // ─── CONNECT ───
  { level: "connect", question: "How do you show someone they matter to you — the actual method?", nl: "Zo laat jij merken dat iemand belangrijk voor je is..." },
  { level: "connect", question: "When did being needed stop feeling good?" },
  { level: "connect", question: "Who taught you the most about how to be close to someone?" },
  { level: "connect", question: "Do you wait to make the first move, even when you're the one missing them?" },
  { level: "connect", question: "How can someone tell you're withdrawing before you've said a word?", nl: "Hoe merken mensen dat jij afstand neemt?" },
  { level: "connect", question: "What do you do when you feel misunderstood — and does it work?", nl: "Wat doe je als je je onbegrepen voelt — en werkt dat?" },
  { level: "connect", question: "Are you listening, or waiting for your turn?", nl: "Luister je echt, of wacht je op je beurt?" },
  { level: "connect", question: "Have you ever worried about someone's relationship with a substance — or had someone worry about yours?", nl: "Heb je je ooit zorgen gemaakt om iemands relatie met een middel — of maakte iemand zich zorgen om die van jou?" },
  { level: "connect", question: "Who did you forgive, without ever telling them?", nl: "Iemand die je hebt vergeven zonder het ooit te zeggen..." },
  { level: "connect", question: "Do you apologize first even when you're not sure you're wrong, just to end it?", nl: "Bied jij als eerste je excuses aan, zelfs als je niet zeker weet dat je fout zit, gewoon om het op te lossen?" },
  { level: "connect", question: "When someone cries in front of you, what happens in you?", nl: "Wat gebeurt er met jou als iemand begint te huilen?" },
  { level: "connect", question: "In which company do you stop performing?", nl: "Bij wie hoef jij niets te bewijzen?" },

  // ─── FRIENDS ───
  { level: "friends", question: "What did your best friendship teach you that no romance did?", nl: "Wat heb je van vriendschap geleerd dat liefde je niet leerde?" },
  { level: "friends", question: "It's 2 a.m. What kind of friend are you?", nl: "Twee uur 's nachts. Welke vriend ben jij?" },
  { level: "friends", question: "Which friendship ended without ever officially ending?", nl: "Een vriendschap die eindigde zonder echt afscheid..." },
  { level: "friends", question: "Which friend gets the honest version of you — and which gets the polite one?", nl: "Wie krijgt de ongefilterde versie van jou?" },
  { level: "friends", question: "Tell about a moment a friend showed up for you in a way you didn't expect.", nl: "Een vriend verraste je precies toen je hem nodig had." },
  { level: "friends", question: "One friend deserves a better version of you...", nl: "Welke vriend verdient meer van jou dan hij krijgt?" },
  { level: "friends", question: "How do you make friends now — and is it harder than it used to be?", nl: "Hoe maak je nu vrienden — en is dat moeilijker dan vroeger?" },
  { level: "friends", question: "Who's a friend you've never had a real conflict with — and do you think that's healthy, or just luck?", nl: "Met welke vriend heb je nooit echt ruzie gehad — en denk je dat dat gezond is, of gewoon geluk?" },
  { level: "friends", question: "Do you trust people by default and get burned occasionally, or trust slowly and rarely get surprised — which one are you?", nl: "Vertrouw je mensen standaard en word je af en toe bedrogen, of vertrouw je langzaam en verras je zelden — wie ben jij?" },
  { level: "friends", question: "The friend I'd call when I'm in real trouble is...", nl: "Wie bel je als het echt misgaat?" },
  { level: "friends", question: "Who can make you laugh when you really don't want to?" },
  { level: "friends", question: "Are you a better friend now than ten years ago — by whose measure?", nl: "Ben je een betere vriend geworden?" },

  // ─── DATE ───
  { level: "date", question: "How do you behave in the first weeks of falling for someone — what's the telltale sign?", nl: "Verliefd worden heeft bij jou altijd dezelfde bijwerkingen. Welke?" },
  { level: "date", question: "Which pattern do you keep bringing into relationships, invited or not?", nl: "Iets dat je telkens weer meeneemt een relatie in..." },
  { level: "date", question: "How do you end things — and how do you want to be left?", nl: "Hoe maak jij een eind aan een relatie — en hoe wil je zelf verlaten worden?" },
  { level: "date", question: "Previous partners undervalued something you offer in love...", nl: "Iets dat jij in een relatie geeft en lang niet altijd terugkrijgt..." },
  { level: "date", question: "A flirt of yours gets shot down — describe the next sixty seconds inside you.", nl: "Je laat merken dat je iemand leuk vindt door..." },
  { level: "date", question: "What relationship rule do you question more than you admit?" },
  { level: "date", question: "Which frightens you more: a relationship costing your freedom, or no relationship at all?", nl: "Wat zou je moeilijker vinden: vastzitten of alleen eindigen?" },
  { level: "date", question: "Have you ever loved two people at the same time — and what did you do about it?" },
  { level: "date", question: "Do you make the first move, or make sure you get chosen?", nl: "Maak jij de eerste zet, of zorg je dat je gekozen wordt?" },
  { level: "date", question: "Which love story — your own or borrowed — do you retell most gladly?", nl: "Een liefdesverhaal dat je blijft koesteren..." },
  { level: "date", question: "What are you like single — and do you like that version?", nl: "Hoe ben jij als je single bent — en bevalt die versie je?" },
  { level: "date", question: "What's the most romantic thing you've attempted that failed completely?", nl: "Een romantisch gebaar dat volledig mislukte..." },

  // ─── ATTRACT ───
  { level: "attract", question: "Someone walks into the room. What makes you look twice?" },
  { level: "attract", question: "What do you find attractive that you'd never admit on a first date?" },
  { level: "attract", question: "Tell about turning someone down — and admit whether you liked being asked." },
  { level: "attract", question: "You tell yourself you have a type. Who do you actually keep ending up with?", nl: "Je zegt dat je een type hebt. Bij wie kom je in werkelijkheid steeds uit?" },
  { level: "attract", question: "What does a barely covered body do that a naked one doesn't?" },
  { level: "attract", question: "Which outfit on someone else has never failed on you — and is it the outfit, or the person wearing it?" },
  { level: "attract", question: "Who's occupying your daydreams — and has anyone inconvenient ever taken that spot?" },
  { level: "attract", question: "Who is your celebrity crush — and does that line up with your actual type?", nl: "Wie is je celebrity crush — en klopt dat met je echte type?" },
  { level: "attract", question: "How much does a voice do for you?" },
  { level: "attract", question: "Are you a different person when you're attracted to someone — and who shows up?" },
  { level: "attract", question: "What do you think the person across from you finds attractive about you — then ask if you're right.", nl: "Wat denk je dat de persoon tegenover je aantrekkelijk aan je vindt — vraag daarna of het klopt." },
  { level: "attract", question: "Confidence: how does someone wear it — walk, voice, stillness — and what does it do to you?" },

  // ─── VALUES ───
  { level: "values", question: "There's something you'd refuse to do, whatever it cost...", nl: "Waarvoor zou je altijd een prijs willen betalen?" },
  { level: "values", question: "Which of your values survives worst under pressure?", nl: "Welke waarde van jou verdwijnt als de druk hoog genoeg wordt?" },
  { level: "values", question: "If you had to guess, what percentage of your life is choice, and what percentage is circumstance?", nl: "Als je moest gokken: welk percentage van je leven is keuze, en welk percentage omstandigheid?" },
  { level: "values", question: "What line have you watched someone cross that told you everything?", nl: "Wanneer vertelde iemands gedrag je alles wat je moest weten?" },
  { level: "values", question: "Quote the sentence your parents repeated — that you now live by, or against." },
  { level: "values", question: "Who gets authority over you faster than you'd like?" },
  { level: "values", question: "When did you stay silent and shouldn't have?", nl: "Een keer dat je had moeten spreken maar zweeg..." },
  { level: "values", question: "What does money let you avoid — a conversation, a choice, a person?", nl: "Wat laat geld je vermijden — een gesprek, een keuze, een persoon?" },
  { level: "values", question: "What are the outer limits of your compassion?", nl: "Waar houdt jouw medeleven op?" },
  { level: "values", question: "What's a rule you break on purpose, every time, without a shred of guilt?" },
  { level: "values", question: "What do you defend in public and doubt in private?" },
  { level: "values", question: "When did competition make you ugly?" },

  // ─── WORLD ───
  { level: "world", question: "What's something the next generation will judge this one harshly for?", nl: "Waarvoor zal de volgende generatie deze hard oordelen?" },
  { level: "world", question: "When did you last actually do something about a problem bigger than you — and did it matter?", nl: "Wanneer deed je voor het laatst echt iets aan een probleem groter dan jezelf — en maakte het uit?" },
  { level: "world", question: "What's something you benefit from that you know isn't fair?" },
  { level: "world", question: "What change in your lifetime still amazes you?", nl: "Welke verandering uit jouw levenstijd blijft bijzonder?" },
  { level: "world", question: "Is there a political position you hold that you find genuinely hard to defend to people who disagree?", nl: "Heb je een politiek standpunt dat je echt moeilijk kunt verdedigen tegenover mensen die het oneens zijn?" },
  { level: "world", question: "Which room first taught you that class exists?" },
  { level: "world", question: "Do people actually change — or just get better at managing what doesn't?" },
  { level: "world", question: "Is there a topic you've just stopped following entirely, because the news stopped doing you any good?", nl: "Is er een onderwerp waar je gewoon helemaal mee bent gestopt, omdat het nieuws je niets meer opleverde?" },
  { level: "world", question: "Is there something happening in the world that genuinely worries you?", nl: "Is er iets in de wereld dat je oprecht zorgen baart?" },
  { level: "world", question: "Is progress real?", nl: "Geloof jij in vooruitgang?" },
  { level: "world", question: "What would you defend about your country to a foreigner — and what not?", nl: "Wat verdedig je als iemand kritiek heeft op jouw land?" },
  { level: "world", question: "Which common belief about how the world works do you think is simply wrong?" },

  // ─── WORK ───
  { level: "work", question: "If you had to train your replacement for exactly one day, what would you make sure they knew that's not in any manual?", nl: "Als je je vervanger precies één dag mocht inwerken, wat zou je zeker vertellen dat in geen enkel handboek staat?" },
  { level: "work", question: "What would you do professionally if status played no role at all?", nl: "Welk werk zou je doen als status niet bestond?" },
  { level: "work", question: "What's the piece of work you're most proud of that nobody applauded?", nl: "Iets waar je trots op bent, maar waar niemand voor klapte..." },
  { level: "work", question: "What's the strangest job you've ever had?", nl: "Wat is de vreemdste baan die je ooit hebt gehad?" },
  { level: "work", question: "Has your idea of success survived contact with reality?", nl: "Wat is er over van jouw idee van succes?" },
  { level: "work", question: "Would you rather be seen as reliable or brilliant — and which one do people actually see you as?", nl: "Zou je liever betrouwbaar of briljant overkomen — en welke van de twee zien mensen echt in jou?" },
  { level: "work", question: "Is ambition something you have or something that has you?", nl: "Wanneer wordt ambitie een last?" },
  { level: "work", question: "What made you choose this field — and is it still the reason you stay?", nl: "Waarom koos je voor dit vak — en is dat nog steeds de reden dat je blijft?" },
  { level: "work", question: "You're genuinely talented at something you'd never turn into a profession...", nl: "Waar ben je opvallend goed in, maar zou je nooit je beroep van maken?" },
  { level: "work", question: "Something would make you walk out tomorrow. What?", nl: "Waar zou jij morgen voor opstappen?" },
  { level: "work", question: "Would you rather stop working today or never be allowed to stop — which one actually scares you more?", nl: "Zou je liever vandaag stoppen met werken, of nooit meer mogen stoppen — welke van de twee vind je écht enger?" },
  { level: "work", question: "What do colleagues learn about you in the first week — and what only after a year?" },

  // ─── DEEP ───
  { level: "deep", question: "What's something you'd tell someone if they asked the right question — but you'd never bring up yourself?", nl: "Wat zou je iemand vertellen als ze de juiste vraag stelden — maar dat je zelf nooit zou beginnen?" },
  { level: "deep", question: "What do you do differently the moment you know you're being watched?", nl: "Wat doe je anders zodra je weet dat er naar je gekeken wordt?" },
  { level: "deep", question: "When did you last cry, and what was underneath it?", nl: "Je laatste tranen gingen eigenlijk over..." },
  { level: "deep", question: "Who left your life better than they found it?", nl: "Wie heeft jouw leven beter achtergelaten dan ze het aantroffen?" },
  { level: "deep", question: "What do you need to hear more often than you admit?", nl: "Wat zou je vaker willen horen dan je toegeeft?" },
  { level: "deep", question: "If you could rerun one conversation from your life, which one?", nl: "Als één gesprek terug mocht komen..." },
  { level: "deep", question: "What skill did you build out of damage control that now feels effortless?" },
  { level: "deep", question: "What do the people who love you have to look past on your worst week?" },
  { level: "deep", question: "Has anyone ever forgiven you in a way that changed how you treat people now?", nl: "Heeft iemand je ooit vergeven op een manier die veranderde hoe je nu met mensen omgaat?" },
  { level: "deep", question: "Slowly, you're making peace with...", nl: "Waar sluit je langzaam vrede mee?" },
  { level: "deep", question: "Which conversation do you keep having — in different rooms, with different people?" },
  { level: "deep", question: "What would you want said about you tonight, if you weren't here to hear it?", nl: "Wat zou je willen dat er vanavond over je gezegd werd, als je het zelf niet kon horen?" },

  // ─── RAW ───
  { level: "raw", question: "Say the thing you censored earlier tonight.", nl: "Iets dat je vandaag hebt ingeslikt..." },
  { level: "raw", question: "Right now you want — first answer, no editing.", nl: "Eerste antwoord. Geen filter. Wat wil je?" },
  { level: "raw", question: "Who are you jealous of, currently?", nl: "Op wie ben je jaloers?" },
  { level: "raw", question: "What are you angry about that you've been calling something else?", nl: "Waar ben je boos over terwijl je het steeds anders noemt?" },
  { level: "raw", question: "What are you pretending to be fine with?", nl: "Waarvan doe je alsof het je niets doet?" },
  { level: "raw", question: "What are you performing right now — and for whom?", nl: "Wat speel je op dit moment — en voor wie?" },
  { level: "raw", question: "Whose way of living makes you question your own choices?", nl: "Wiens manier van leven laat jou aan je eigen keuzes twijfelen?" },
  { level: "raw", question: "What's the pettiest thing you've felt this evening?", nl: "Wat is het kleinzieligste dat je vanavond hebt gevoeld?" },
  { level: "raw", question: "What did you get away with this week?" },
  { level: "raw", question: "Who have you been unfair to lately?", nl: "Tegen wie ben je de laatste tijd onrechtvaardig geweest?" },
  { level: "raw", question: "What are you afraid this game will ask you?", nl: "Welke vraag hoop je dat vanavond niet langskomt?" },
  { level: "raw", question: "What's something you've decided isn't worth saying — but haven't fully let go of?" },

  // ─── GRIEF ───
  { level: "grief", question: "One loss you're still not finished with...", nl: "Een verlies dat nog altijd niet op zijn plek is gevallen..." },
  { level: "grief", question: "What did you grieve before it even happened?" },
  { level: "grief", question: "Who do you still talk to that can no longer answer?", nl: "Met wie praat je soms nog, ondanks alles?" },
  { level: "grief", question: "What surprised you about how you grieved?", nl: "Wat verbaasde je aan de manier waarop je rouwde?" },
  { level: "grief", question: "Who showed up when you lost something — and who didn't?", nl: "Wie stond er voor je toen je iets verloor — en wie niet?" },
  { level: "grief", question: "What did grief change about what you find important?", nl: "Wat heeft verdriet veranderd aan wat jij belangrijk vindt?" },
  { level: "grief", question: "What do you do with grief — do you move through it, around it, or does it move through you?", nl: "Wat doe je met verdriet — ga je erdoorheen, eromheen, of gaat het door jou heen?" },
  { level: "grief", question: "Which object holds a loss for you?", nl: "Een voorwerp dat meer bewaart dan zichzelf..." },
  { level: "grief", question: "Because of them, you still do something nobody knows about...", nl: "Iemand leeft voort in iets wat jij nog steeds doet." },
  { level: "grief", question: "What haven't you allowed yourself to mourn yet?" },
  { level: "grief", question: "What did you lose that wasn't a person?", nl: "Wat ben je kwijtgeraakt dat geen mens was?" },
  { level: "grief", question: "After they were gone, you had to become...", nl: "Na dat verlies moest jij..." },

  // ─── FAMILY ───
  { level: "family", question: "Which family relationship costs you the most — and what does it give back?", nl: "Welke familieband vraagt het meest van je?" },
  { level: "family", question: "What's the unspoken rule in your family that everyone follows and no one names?", nl: "Welke ongeschreven regel volgt iedereen in jouw familie zonder die ooit te benoemen?" },
  { level: "family", question: "What did a parent give you that you only learned to value late?", nl: "Iets van je ouders dat je pas later bent gaan waarderen." },
  { level: "family", question: "Where does your family still see an old version of you?", nl: "Bij wie in de familie ben je nog steeds niet helemaal volwassen?" },
  { level: "family", question: "What does your family argue about that doesn't matter at all?", nl: "Waar maakt jouw familie ruzie over terwijl het nergens over gaat?" },
  { level: "family", question: "Which inherited trait do you watch for in the mirror, with dread?", nl: "Op welke eigenschap hoop je níét te gaan lijken?" },
  { level: "family", question: "Your parents are getting old. What is that doing to you?", nl: "Je ouders worden ouder. Wat doet dat met je?" },
  { level: "family", question: "Who became family without being family?" },
  { level: "family", question: "Who in your family knows you best — and do they know that?", nl: "Wie in je familie kent jou het best — en weet diegene dat?" },
  { level: "family", question: "What role do you play in your family — and is it one you chose?", nl: "Welke rol speel jij in je familie — en heb je die zelf gekozen?" },
  { level: "family", question: "What kind of parent are you — or would actually be? The honest guess, not the hoped-for one." },
  { level: "family", question: "Did you want children — and has that changed?" },

  // ─── US ───
  { level: "us", question: "What did you think of me the first time we met — unedited?", nl: "De eerste indruk die je van mij had..." },
  { level: "us", question: "What question have you wanted to ask me but haven't?", nl: "Iets dat je nieuwsgierig maakt naar mij, maar nooit hebt gevraagd..." },
  { level: "us", question: "What do we have in common that neither of us has named?", nl: "Wat herkennen wij in elkaar zonder dat we het ooit benoemd hebben?" },
  { level: "us", question: "What do you think I need to hear right now?", nl: "Een waarheid die ik volgens jou moet horen..." },
  { level: "us", question: "What did I do that affected you more than I probably realise?", nl: "Wanneer had ik meer invloed op je dan ik vermoed?" },
  { level: "us", question: "What's one thing you know about me that I don't know you know?" },
  { level: "us", question: "Quote something I once said that stuck with you." },
  { level: "us", question: "Which of my habits have you quietly adapted to?", nl: "Een gewoonte van mij die ongemerkt op jou is afgegeven..." },
  { level: "us", question: "What would you warn someone about me — kindly?", nl: "Waar zou je iemand vriendelijk voor waarschuwen als het over mij gaat?" },
  { level: "us", question: "What do you hope I never change?", nl: "Wat hoop je dat ik nooit verlies?" },
  { level: "us", question: "What's the most me thing I've ever done?", nl: "Wat is het meest ik-dingetje dat ik ooit heb gedaan?" },
  { level: "us", question: "What would you tell me if you knew I could actually hear it right now?" },

  // ─── USFRIEND ───
  { level: "usfriend", question: "Which moment made this friendship real for you?", nl: "Wanneer werd dit meer dan zomaar een vriendschap?" },
  { level: "usfriend", question: "What do we never do that you wish we did?" },
  { level: "usfriend", question: "What do I still not understand about you?" },
  { level: "usfriend", question: "What do you think I need from this friendship that I've never said?" },
  { level: "usfriend", question: "How has this friendship changed you?", nl: "Wie ben jij geworden door deze vriendschap?" },
  { level: "usfriend", question: "What's your favourite story about us that you tell other people?", nl: "Welk verhaal over ons vertel je het liefst?" },
  { level: "usfriend", question: "What would end this friendship?", nl: "Wat zou deze vriendschap kunnen breken?" },
  { level: "usfriend", question: "What would you trust me with that you'd trust no one else?" },
  { level: "usfriend", question: "When were you proudest of me?" },
  { level: "usfriend", question: "When have I made you laugh hardest?" },
  { level: "usfriend", question: "If this friendship had a title, what would it be?", nl: "Als deze vriendschap een titel had..." },
  { level: "usfriend", question: "Who would you introduce me to — and why?", nl: "Aan wie zou je mij voorstellen — en waarom?" },

  // ─── USLOVE ───
  { level: "uslove", question: "Name the thing I give you that you'd miss most.", nl: "Wat zou je van mij het meest missen?" },
  { level: "uslove", question: "You've stopped asking me for something — what is it?", nl: "Waar ben je gestopt met naar te vragen?" },
  { level: "uslove", question: "What are we both avoiding right now?", nl: "Waar lopen we allebei omheen?" },
  { level: "uslove", question: "When did you last fall for me again, even briefly?", nl: "Wanneer werd je opnieuw een beetje verliefd op mij?" },
  { level: "uslove", question: "How do you know I love you — what actually tells you?", nl: "Waaraan merk je dat ik van je hou — wat verraadt het?" },
  { level: "uslove", question: "What did you decide about us before I had any say in it?", nl: "Waarover had je al besloten voordat ik iets mocht vinden?" },
  { level: "uslove", question: "Is there a version of me you miss?", nl: "Naar welke versie van mij verlang je soms terug?" },
  { level: "uslove", question: "Tell me what you'd change about us if I couldn't take it personally.", nl: "Stel dat ik me niet verdedigde. Wat zou je aan ons veranderen?" },
  { level: "uslove", question: "Where am I still a mystery to you?", nl: "Waar ken jij mij nog niet?" },
  { level: "uslove", question: "Pick the fight we should have more honestly.", nl: "Welke ruzie voeren wij niet eerlijk genoeg?" },
  { level: "uslove", question: "When do you feel most like yourself with me?", nl: "Wanneer ben jij het meest jezelf bij mij?" },
  { level: "uslove", question: "When did you decide I was worth it?" },

  // ─── USINTIMATE ───
  { level: "usintimate", question: "What do you think I want from you that I haven't asked for?" },
  { level: "usintimate", question: "Replay a moment between us — out loud." },
  { level: "usintimate", question: "What do you wish I understood about your desire?" },
  { level: "usintimate", question: "Point to where you want to be kissed, right now." },
  { level: "usintimate", question: "When do you feel most sexually connected to me?" },
  { level: "usintimate", question: "What do I do that works better than I know?" },
  { level: "usintimate", question: "Show me, with my hand, how you want to be touched." },
  { level: "usintimate", question: "When our wanting doesn't line up, what do you do?", nl: "Als ons verlangen niet gelijk loopt, wat doe jij dan?" },
  { level: "usintimate", question: "Would you want to know if I were drawn to someone else? Ask me the same.", nl: "Zou je willen weten als ik me tot iemand anders aangetrokken voelde? Vraag mij hetzelfde." },
  { level: "usintimate", question: "What have you been wanting to try with me but haven't said?" },
  { level: "usintimate", question: "When do you catch me wanting you — and what does it make you do?" },
  { level: "usintimate", question: "What do you hold back with me — and what would it take to stop?" },

  // ─── SHADOW ───
  { level: "shadow", question: "You lie most consistently about...", nl: "Waar maak jij de waarheid regelmatig iets mooier?" },
  { level: "shadow", question: "Quote the cruelest thing you've ever actually said." },
  { level: "shadow", question: "The you that comes out at your worst — honestly...", nl: "Op je slechtst ben jij iemand die..." },
  { level: "shadow", question: "People believe your presentation. What does that let you do?", nl: "Mensen geloven je voorkomen. Wat kun je daardoor doen?" },
  { level: "shadow", question: "Which emotion do you fake best?", nl: "Welke emotie kun jij overtuigend spelen?" },
  { level: "shadow", question: "Tell about hurting someone without meaning to.", nl: "Een keer dat je iemand pijn deed zonder dat te willen..." },
  { level: "shadow", question: "Which vice has survived every attempt to quit it?", nl: "Welke slechte gewoonte blijkt onverwoestbaar?" },
  { level: "shadow", question: "Has your anger ever frightened someone?", nl: "Wanneer schrok iemand van jouw boosheid?" },
  { level: "shadow", question: "What would make you safeword out of life, if life had one?" },
  { level: "shadow", question: "When did you last choose comfort over integrity?", nl: "Wanneer koos je voor comfort boven je principes?" },
  { level: "shadow", question: "What are you doing right up until someone walks in?" },
  { level: "shadow", question: "Which apology do you still owe?", nl: "Tegen wie heb jij nog iets goed te maken?" },

  // ─── WISH ───
  { level: "wish", question: "The life you almost lived — how close did it come?" },
  { level: "wish", question: "What did you once wish for that you now have?", nl: "Wat wenste je ooit en heb je nu?" },
  { level: "wish", question: "If I were braver, I would already have...", nl: "Als lef geen rol speelde..." },
  { level: "wish", question: "Which longing have you domesticated into a hobby?", nl: "Welke droom heb je klein gemaakt zodat hij beter paste?" },
  { level: "wish", question: "What's the gap between your current life and the one part of you expects?", nl: "Waar botst je huidige leven met wat je ooit verwachtte?" },
  { level: "wish", question: "What have you been quietly rooting for, in your own life?" },
  { level: "wish", question: "If you fast-forwarded five good years, what would you want to see?" },
  { level: "wish", question: "What's a life you've seen from the outside and thought: \"how did they end up there?\"", nl: "Wiens leven zag je van buitenaf en dacht je: hoe zijn ze daar terechtgekomen?" },
  { level: "wish", question: "What's a skill or trait you're actively working on right now that nobody's asked you to?", nl: "Aan welke vaardigheid of eigenschap werk je nu actief, zonder dat iemand je dat gevraagd heeft?" },
  { level: "wish", question: "What do you want for someone else that you can't give them?", nl: "Wat gun je iemand anders dat je hem of haar niet kunt geven?" },
  { level: "wish", question: "What do you want that would surprise the people who know you?" },
  { level: "wish", question: "What did you want last year that you've already stopped wanting?", nl: "Waar verlangde je vorig jaar nog naar?" },

  // ─── SKIN ───
  { level: "flesh", question: "Some touch undoes you. Describe it." },
  { level: "flesh", question: "What's something you thought you'd never enjoy until you actually experienced it?" },
  { level: "flesh", question: "Afterwards, still tangled up — how do you like to come down?" },
  { level: "flesh", question: "Walk me through undressing someone — the order, the pace, what you notice." },
  { level: "flesh", question: "Reconstruct your smoothest pickup ever." },
  { level: "flesh", question: "A kiss you can still feel when you think of it — take me there." },
  { level: "flesh", question: "What does a hand around your throat — or on the back of your neck — do to you?" },
  { level: "flesh", question: "How far do you go in public — what are you okay with people seeing?" },
  { level: "flesh", question: "Your hands on someone's body — where do they go first, and where do they linger?" },
  { level: "flesh", question: "What makes you feel completely safe with someone sexually?" },
  { level: "flesh", question: "In the moment, how do you make what you want known — words, hands, or just taking it?" },
  { level: "flesh", question: "How much do you enjoy making someone wait before you touch them?" },

  // ─── CARNAL ───
  { level: "carnal", question: "What pulls you out of your body during sex, when it happens?" },
  { level: "carnal", question: "What do you want more of in bed that you rarely get?" },
  { level: "carnal", question: "What makes you laugh in bed?" },
  { level: "carnal", question: "What's your sexual superpower — and the night it proved you right?" },
  { level: "carnal", question: "When did sex last turn you into pure body — no thoughts, just flow — and what do you remember?" },
  { level: "carnal", question: "What sound — yours or theirs — tips you over the edge?" },
  { level: "carnal", question: "Do you enjoy giving pleasure more, receiving it more, or does the split not matter to you?" },
  { level: "carnal", question: "Teeth, nails, grip, hair — what evidence do you want to find on yourself the next day?" },
  { level: "carnal", question: "When does sex stop being about you — and is that a good thing?" },
  { level: "carnal", question: "What have you never asked for because it's better getting it without asking?" },
  { level: "carnal", question: "Which of your turn-ons did you find through porn instead of real life?" },
  { level: "carnal", question: "What kind of erotica — written, told, or visual — pulls you in, and what does that tell you about your own taste?" },

  // ─── BLUNT ───
  { level: "bare", question: "Sex — how important is it, honestly, in the whole of your life?" },
  { level: "bare", question: "Is solo sex, for you, self-care or an escape hatch — and how often do you reach for it?" },
  { level: "bare", question: "When has your body not done what you wanted in bed — and what did you do?" },
  { level: "bare", question: "What do people consistently get wrong about your sexuality?" },
  { level: "bare", question: "What did you believe about sex that turned out to be nonsense?" },
  { level: "bare", question: "Your count: do you know it? Break it down if you dare — relationships, flings, one-night stands." },
  { level: "bare", question: "Tell about the moment sex went most embarrassingly wrong." },
  { level: "bare", question: "What does sexual fulfilment feel like — and do you have it now?" },
  { level: "bare", question: "Is an age gap something that would actually get to you, or just something you'd expect to have to explain to other people?" },
  { level: "bare", question: "Tell the story of the most outrageous sexual situation you've found yourself in." },
  { level: "bare", question: "The most memorable places sex has happened — the most beautiful, and the strangest?" },
  { level: "bare", question: "What's the longest you've gone without sex — and how was that?" },

  // ─── KINKS ───
  { level: "kinks", question: "What does it feel like to be completely at someone's mercy — or to have someone completely at yours?" },
  { level: "kinks", question: "Watching, or being watched — which does more for you?" },
  { level: "kinks", question: "Can pain — given or taken — carry pleasure for you, and what's the pull?" },
  { level: "kinks", question: "Alone or with someone — what does a toy give you that you otherwise wouldn't get?" },
  { level: "kinks", question: "What do you still keep quiet about in bed, and what makes you keep it that way?" },
  { level: "kinks", question: "Is there a kink or fantasy you have that you've never fully acted on?" },
  { level: "kinks", question: "What kind of words instantly turn you on?" },
  { level: "kinks", question: "Who do you turn into in bed — and what does someone do to bring them out?" },
  { level: "kinks", question: "Undressed and having to wait — what does anticipation do to you?" },
  { level: "kinks", question: "When did \"yes\" turn into \"actually, no\" while it was already happening?" },
  { level: "kinks", question: "Who introduced you to something you'd never have found or tried alone?" },
  { level: "kinks", question: "More than two — does it appeal, and what's the pull?" },

  // ─── ABYSS ───
  { level: "abyss", question: "What did you once think was extreme that's now a Tuesday, and what still gives you pause on a Saturday night?" },
  { level: "abyss", question: "What does a room full of people doing this know that nobody outside it does?" },
  { level: "abyss", question: "What does going to the extreme give you that gentle never could?" },
  { level: "abyss", question: "Tell about a scene that changed you." },
  { level: "abyss", question: "Has your body ever said yes while something deeper said no — and how did you find out?" },
  { level: "abyss", question: "In the darkest rooms, what's the gentlest thing that happens?" },
  { level: "abyss", question: "Tell about the safeword that got used — or the one that should have been." },
  { level: "abyss", question: "Where did you find out you had a limit?" },
  { level: "abyss", question: "What kind of trust does going that far actually take?" },
  { level: "abyss", question: "What did you consent to that you didn't actually want?" },
  { level: "abyss", question: "Who in your normal life knows about this side of you — do they understand, and who will never find out?" },
  { level: "abyss", question: "What is something considered 'taboo' by society that you actually find quite appealing?" },
];

// ── REFERENCE SETS — canonical sequences, deck-independent (like Colbert) ──
// Arthur Aron's 36 questions (the closeness study, 1997) — order is the design.
const ARON_CARDS = [
  { level: "aron", question: "Given the choice of anyone in the world, whom would you want as a dinner guest?" },
  { level: "aron", question: "Would you like to be famous? In what way?" },
  { level: "aron", question: "Before making a telephone call, do you ever rehearse what you are going to say? Why?" },
  { level: "aron", question: "What would constitute a “perfect” day for you?" },
  { level: "aron", question: "When did you last sing to yourself? To someone else?" },
  { level: "aron", question: "If you were able to live to the age of 90 and retain either the mind or the body of a 30-year-old for the last 60 years of your life, which would you want?" },
  { level: "aron", question: "Do you have a secret hunch about how you will die?" },
  { level: "aron", question: "Name three things you and your partner appear to have in common." },
  { level: "aron", question: "For what in your life do you feel most grateful?" },
  { level: "aron", question: "If you could change anything about the way you were raised, what would it be?" },
  { level: "aron", question: "Take four minutes and tell your partner your life story in as much detail as possible." },
  { level: "aron", question: "If you could wake up tomorrow having gained any one quality or ability, what would it be?" },
  { level: "aron", question: "If a crystal ball could tell you the truth about yourself, your life, the future, or anything else, what would you want to know?" },
  { level: "aron", question: "Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?" },
  { level: "aron", question: "What is the greatest accomplishment of your life?" },
  { level: "aron", question: "What do you value most in a friendship?" },
  { level: "aron", question: "What is your most treasured memory?" },
  { level: "aron", question: "What is your most terrible memory?" },
  { level: "aron", question: "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?" },
  { level: "aron", question: "What does friendship mean to you?" },
  { level: "aron", question: "What roles do love and affection play in your life?" },
  { level: "aron", question: "Alternate sharing something you consider a positive characteristic of your partner. Share a total of five items." },
  { level: "aron", question: "How close and warm is your family? Do you feel your childhood was happier than most other people’s?" },
  { level: "aron", question: "How do you feel about your relationship with your mother?" },
  { level: "aron", question: "Make three true “we” statements each. For instance, “We are both in this room feeling…”" },
  { level: "aron", question: "Complete this sentence: “I wish I had someone with whom I could share…”" },
  { level: "aron", question: "If you were going to become a close friend with your partner, please share what would be important for him or her to know." },
  { level: "aron", question: "Tell your partner what you like about them; be very honest this time, saying things that you might not say to someone you’ve just met." },
  { level: "aron", question: "Share with your partner an embarrassing moment in your life." },
  { level: "aron", question: "When did you last cry in front of another person? By yourself?" },
  { level: "aron", question: "Tell your partner something that you like about them already." },
  { level: "aron", question: "What, if anything, is too serious to be joked about?" },
  { level: "aron", question: "If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone? Why haven’t you told them yet?" },
  { level: "aron", question: "Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?" },
  { level: "aron", question: "Of all the people in your family, whose death would you find most disturbing? Why?" },
  { level: "aron", question: "Share a personal problem and ask your partner’s advice on how he or she might handle it. Also, ask your partner to reflect back to you how you seem to be feeling about the problem you have chosen." },
];
// Priya Parker's magical questions — group framing removed from three of them.
const MAGIC_CARDS = [
  { level: "magic", question: "What’s a path you almost took but didn’t?" },
  { level: "magic", question: "What song would they play at your funeral?" },
  { level: "magic", question: "What’s a dish you loved as a child and maybe forgot about? Who made it?" },
  { level: "magic", question: "What gift would you give to aliens on behalf of humanity?" },
  { level: "magic", question: "If you were a fly on the wall, what would you love to hear people saying about you?" },
  { level: "magic", question: "If you could bring one food to share right now, what would it be?" },
  { level: "magic", question: "What’s your anti–pet peeve — a small thing that gives you disproportionate joy?" },
  { level: "magic", question: "What are you an evangelist for?" },
  { level: "magic", question: "Has someone else accomplished something you’re more proud of than anything you’ve done yourself?" },
  { level: "magic", question: "What talent do you have that you would never turn into a profession?" },
  { level: "magic", question: "What does the way you dress say about you?" },
  { level: "magic", question: "What would you want your grandchildren to know about this period of history?" },
  { level: "magic", question: "If you went back to school, what would you study?" },
  { level: "magic", question: "What were you bad at as a kid that you’re actually good at now?" },
  { level: "magic", question: "Where in your life do you need more glitter?" },
  { level: "magic", question: "If a burger were named after you, what would be on it?" },
  { level: "magic", question: "What is your favorite building where you live — and why?" },
  { level: "magic", question: "If you had a lifetime supply of anything, what would you choose?" },
  { level: "magic", question: "What pilgrimage would you like to make?" },
  { level: "magic", question: "Which artist’s work would you never hang on your wall, even if it were free?" },
  { level: "magic", question: "If you were a Jeopardy category, what would it be?" },
  { level: "magic", question: "What would your childhood friends be most surprised to learn about your career?" },
  { level: "magic", question: "If you could have a song play every time you walk into a room, what would it be?" },
  { level: "magic", question: "What was a sliding-door moment in your life — a small choice that changed everything?" },
  { level: "magic", question: "Which of your scars has the best story?" },
  { level: "magic", question: "What are the three apps you use most — and what do they say about you?" },
  { level: "magic", question: "What’s the nicest compliment you’ve ever received?" },
  { level: "magic", question: "What’s something you’ve made that you’re proud of?" },
  { level: "magic", question: "What tradition did you grow up with that you’ve kept?" },
  { level: "magic", question: "What’s one thing you’re looking forward to?" },
];

const ALL_CARDS = NEWDECK_CARDS.concat(COLBERT_CARDS, ARON_CARDS, MAGIC_CARDS);
const DECK_LEVELS = new Set(ALL_CARDS.map(c => c.level));;
